# Generated by Django 5.0.7 on 2024-07-25 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_recipe_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'Countries'},
        ),
        migrations.AddField(
            model_name='ingredient',
            name='ingredients',
            field=models.TextField(blank=True, null=True),
        ),
    ]
