# Generated by Django 5.0.7 on 2024-07-29 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_recipe_country'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ('-id',)},
        ),
        migrations.AddField(
            model_name='recipe',
            name='rating',
            field=models.IntegerField(default=1),
        ),
    ]
