# Generated by Django 5.0.7 on 2024-07-30 07:17

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_recipe_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='make',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
